#!/bin/bash

if [ -z "$1" ]; then
  echo "Usage: $0 <USERNAME>"
  exit 1
fi

USERNAME="$1"

docker buildx create --use

ARCH="x86_64"
docker buildx build \
  --platform linux/amd64 \
  -f manylinux/Dockerfile.manylinux_2_28 \
  --build-arg ARCH=${ARCH} \
  --push \
  -t  "ghcr.io/${USERNAME}/qupled_manylinux_${ARCH}" \
  .

ARCH="aarch64"
docker buildx build \
  --platform linux/arm64 \
  -f manylinux/Dockerfile.manylinux_2_28 \
  --build-arg ARCH=${ARCH} \
  --push \
  -t "ghcr.io/${USERNAME}/qupled_manylinux_${ARCH}" \
  .