[tox]
envlist = test, examples, unit, native, integration

[testenv]
passenv = WHEEL_FILE, OpenMP_ROOT
skip_install = true
changedir = {envtmpdir}
deps =
    pytest
    pytest-mock
    {env:WHEEL_FILE}

[testenv:test]
commands =
    pytest {toxinidir}/tests -v

[testenv:unit]
commands =
    pytest -m unit {toxinidir}/tests -v

[testenv:native]
commands =
    pytest -m native {toxinidir}/tests -v

[testenv:integration]
allowlist_externals = cp
commands_pre =
    cp -r {toxinidir}/examples/docs {envtmpdir}
commands =
    pytest -m integration {toxinidir}/tests -v

[testenv:examples]
allowlist_externals = cp
commands_pre =
    cp -r {toxinidir}/examples/docs {envtmpdir}
commands =
    pytest {toxinidir}/examples -v

