[tox]
envlist = test, unit, native, integration

[testenv]
passenv = OpenMP_ROOT
changedir = {envtmpdir}
extras = test
allowlist_externals = cp

[testenv:test]
commands_pre =
    cp -r {toxinidir}/examples/docs {envtmpdir}
commands =
    pytest {toxinidir}/tests -v

[testenv:unit]
commands =
    pytest -m unit {toxinidir}/tests -v

[testenv:native]
commands =
    pytest -m native {toxinidir}/tests -v

[testenv:integration]
commands_pre =
    cp -r {toxinidir}/examples/docs {envtmpdir}
commands =
    pytest -m integration {toxinidir}/tests -v
