from enum import Enum
from qupled.database.database_handler import DataBaseHandler


class OutputType(Enum):
    """
    An enumerator representing the output types.

    Values:

       ``SCHEME``: Output from a scheme calculation.

       ``FINITE_SIZE_CORRECTION``: Output from a finite size correction calculation.
    """

    SCHEME = "scheme"
    FINITE_SIZE_CORRECTION = "finite_size_correction"


class DataBase:
    """Class to read and delete data from a database generated by qupled"""

    @staticmethod
    def inspect_runs(type: OutputType, database_name: str | None = None) -> dict:
        """
        Reads runs from the database and returns the content in the form of a dictionary.

        Args:
            type: The type of output to inspect.
            database_name: Name of the database to read from. Defaults to None.

        Returns:
            dict: A dictionary whose keys are the run IDs and values are the corresponding run information.
        """
        db_handler = DataBaseHandler(database_name)
        if type == OutputType.SCHEME:
            return db_handler.scheme_tables.inspect_runs()
        elif type == OutputType.FINITE_SIZE_CORRECTION:
            return db_handler.fsc_tables.inspect_runs()
        else:
            return {}

    @staticmethod
    def read_run(
        type: OutputType,
        run_id: int,
        database_name: str | None = None,
        input_names: list[str] | None = None,
        result_names: list[str] | None = None,
    ) -> dict:
        """
        Reads a specific run from the database.

        Args:
            type: The type of output to read.
            run_id: The ID of the run to read.
            database_name: The name of the database to read from. Defaults to None.
            input_names: A list of input names to retrieve. Defaults to None.
            result_names: A list of result names to retrieve. Defaults to None.

        Returns:
            dict: A dictionary containing the run data.
        """
        db_handler = DataBaseHandler(database_name)
        if type == OutputType.SCHEME:
            return db_handler.scheme_tables.get_run(run_id, input_names, result_names)
        elif type == OutputType.FINITE_SIZE_CORRECTION:
            return db_handler.fsc_tables.get_run(run_id, input_names, result_names)
        else:
            return {}

    @staticmethod
    def read_inputs(
        type: OutputType,
        run_id: int,
        database_name: str | None = None,
        names: list[str] | None = None,
    ) -> dict:
        """
        Reads inputs from the database and returns the content in the form of a dictionary.

        Args:
            type: The type of output to read inputs for.
            run_id: Identifier of the run to read inputs for.
            database_name: Name of the database to read from. Defaults to None.
            names: A list of quantities to read. Defaults to None, which reads all available quantities.

        Returns:
            dict: A dictionary whose keys are the quantities listed in names and values are the corresponding inputs.
        """
        db_handler = DataBaseHandler(database_name)
        if type == OutputType.SCHEME:
            return db_handler.scheme_tables.get_inputs(run_id, names)
        elif type == OutputType.FINITE_SIZE_CORRECTION:
            return db_handler.fsc_tables.get_inputs(run_id, names)
        else:
            return {}

    @staticmethod
    def read_results(
        type: OutputType,
        run_id: int,
        database_name: str | None = None,
        names: list[str] | None = None,
    ) -> dict:
        """
        Reads results from the database and returns the content in the form of a dictionary.

        Args:
            type: The type of output to read results for.
            run_id: Identifier of the run to read results for.
            database_name: Name of the database to read from. Defaults to None.
            names: A list of quantities to read. Defaults to None, which reads all available quantities.

        Returns:
            dict: A dictionary whose keys are the quantities listed in names and values are the corresponding results.
        """
        db_handler = DataBaseHandler(database_name)
        if type == OutputType.SCHEME:
            return db_handler.scheme_tables.get_results(run_id, names)
        elif type == OutputType.FINITE_SIZE_CORRECTION:
            return db_handler.fsc_tables.get_results(run_id, names)
        else:
            return {}

    # Delete results from the database
    @staticmethod
    def delete_run(type: OutputType, run_id: int, database_name: str | None = None):
        """
        Deletes a run entry from the database based on the provided run ID.

        Args:
            type: The type of output to delete.
            run_id: The unique identifier of the run to be deleted.
            database_name: The name of the database to connect to. Defaults to None.
        """
        db_handler = DataBaseHandler(database_name)
        if type == OutputType.SCHEME:
            db_handler.scheme_tables.delete_run(run_id)
        elif type == OutputType.FINITE_SIZE_CORRECTION:
            db_handler.fsc_tables.delete_run(run_id)
