name: Build & Test

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'
  pull_request:

env:
  PYTHON_VENV_ROOT: ${{ github.workspace }}/python-venv

jobs:
  python_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python3 -m venv ${PYTHON_VENV_ROOT}
        source ${PYTHON_VENV_ROOT}/bin/activate
        ./devtool install-deps

    - name: Build package
      run: |
        source ${PYTHON_VENV_ROOT}/bin/activate
        ./devtool build

    - name: Run unit tests
      run: |
        source ${PYTHON_VENV_ROOT}/bin/activate
        ./devtool test unit

    - name: Run native tests
      if: github.event_name == 'pull_request'
      run: |
        source ${PYTHON_VENV_ROOT}/bin/activate
        ./devtool test native

  cpp_tests_with_mpi:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python3 -m venv ${PYTHON_VENV_ROOT}
        source ${PYTHON_VENV_ROOT}/bin/activate
        ./devtool install-deps

    - name: Run cpp tests with MPI
      run: |
        source ${PYTHON_VENV_ROOT}/bin/activate
        ./devtool test cpp --use-mpi

  cpp_tests_without_mpi:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python3 -m venv ${PYTHON_VENV_ROOT}
        source ${PYTHON_VENV_ROOT}/bin/activate
        ./devtool install-deps

    - name: Run cpp tests without MPI
      run: |
        source ${PYTHON_VENV_ROOT}/bin/activate
        ./devtool test cpp
