name: Build and Test (no MPI)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  build_and_test:
  
    runs-on: macos-13
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        brew update
        brew install cmake gsl libomp openmpi fmt boost-python3
        pip3 install --upgrade pip
        pip3 install -r python/requirements.txt
        
    - name: Configure CMake
      run: |
        export OpenMP_ROOT=$(brew --prefix)/opt/libomp
        cmake -Bbuild -H. -DCMAKE_BUILD_TYPE=Release -DUSE_MPI=OFF
        
    - name: Build
      run: |
        cmake --build build --config Release
        
    - name: Tests
      run: |
        cd build
        pytest -k "not test_examples" tests
