name: Build macOS Wheels

on:
  workflow_call:

jobs:
  build-macos-wheels:
    name: Build macOS wheels (${{ matrix.arch }})
    strategy:
      matrix:
        include:
          # - arch: arm64
          #   runner: macos-latest
          - arch: x86_64
            runner: macos-13

    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set build version
        run: ./devtool update-version ${{ github.ref_name }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build dependencies
        run: ./devtool install-deps

      - name: Set OpenMP_ROOT
        run: |
          BREW_PREFIX=$(brew --prefix)
          echo "OpenMP_ROOT=$BREW_PREFIX/opt/libomp" >> $GITHUB_ENV

      - name: Install cibuildwheel
        run: python -m pip install --upgrade cibuildwheel

      - name: Build wheels with cibuildwheel
        run: cibuildwheel --output-dir wheelhouse
        env:
          CIBW_PLATFORM: macos
          CIBW_ARCHS_MACOS: ${{ matrix.arch }}
          # MACOSX_DEPLOYMENT_TARGET: "14.0"

      - name: Upload built wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-macos-${{ matrix.arch }}
          path: wheelhouse/*.whl
