name: Build & Test (macOS)

on:
  workflow_call:

env:
  PYTHON_VENV_ROOT: ${{ github.workspace }}/python-venv

jobs:

  build_and_test:

    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        brew update
        brew install cmake gsl libomp fmt boost-python3
        python3 -m venv ${PYTHON_VENV_ROOT}

    - name: Build
      run: |
        source ${PYTHON_VENV_ROOT}/bin/activate
        pip3 install --upgrade pip
        pip3 install build setuptools
        export OpenMP_ROOT=$(brew --prefix)/opt/libomp	
        ./devtool build --nompi

    - name: Tests
      run: |
        source ${PYTHON_VENV_ROOT}/bin/activate
        pip3 install tox
        ./devtool test
