name: Build & Test

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'
  pull_request:
jobs:
  python_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Set up uv
      uses: astral-sh/setup-uv@v5

    - name: Install dependencies
      run: ./devtool install-deps

    - name: Build package
      run: ./devtool build

    - name: Run unit tests
      run: ./devtool test unit

    - name: Run native tests
      if: github.event_name == 'pull_request'
      run: ./devtool test native

  cpp_tests_with_mpi:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Set up uv
      uses: astral-sh/setup-uv@v5

    - name: Install dependencies
      run: ./devtool install-deps

    - name: Run cpp tests with MPI
      run: ./devtool test cpp --use-mpi

  cpp_tests_without_mpi:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Set up uv
      uses: astral-sh/setup-uv@v5

    - name: Install dependencies
      run: ./devtool install-deps

    - name: Run cpp tests without MPI
      run: ./devtool test cpp
