name: Build & Test (macOS-MPI)

on:
  workflow_call:
    inputs:
      upload-artifact:
        required: true
        type: string

env:
  PYTHON_VENV_ROOT: ${{ github.workspace }}/python-venv

jobs:

  build_and_test:

    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        brew update
        brew install cmake gsl libomp openmpi fmt boost-python3
        python3 -m venv ${PYTHON_VENV_ROOT}
        pip3 install --upgrade pip

    - name: Build
      run: |
        source ${PYTHON_VENV_ROOT}/bin/activate
        export OpenMP_ROOT=$(brew --prefix)/opt/libomp
        pip3 install --upgrade pip
        pip3 install build setuptools
        ./devtool build

    - name: Tests
      run: |
        source ${PYTHON_VENV_ROOT}/bin/activate
        pip3 install tox
        ./devtool test

    - name: Upload artifact
      if: ${{ success() && inputs.upload-artifact == 'true' }}
      uses: actions/upload-artifact@v3
      with:
        name: qupled-linux
        path: dist