name: Build & Test (Linux-MPI)

on:
  workflow_call:

env:
  PYTHON_VENV_ROOT: ${{ github.workspace }}/python-venv

jobs:

  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake libboost-all-dev libopenmpi-dev libgsl-dev libomp-dev libfmt-dev python3-dev
        python3 -m venv ${PYTHON_VENV_ROOT}

    - name: Build
      run: |
        source ${PYTHON_VENV_ROOT}/bin/activate
        pip3 install --upgrade pip
        pip3 install build setuptools
        ./devtool build

    - name: Tests
      run: |
        source ${PYTHON_VENV_ROOT}/bin/activate
        pip3 install tox
        ./devtool test
