name: Build & Test (Linux-MPI)

on:
  push:
  pull_request:
    branches:
      - master

env:
  PYTHON_VENV_ROOT: ${{ github.workspace }}/python-venv
  
jobs:

  build_and_test:
  
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake libboost-all-dev libopenmpi-dev libgsl-dev libomp-dev libfmt-dev python3-dev
        python3 -m venv ${PYTHON_VENV_ROOT}
        source ${PYTHON_VENV_ROOT}/bin/activate
        pip3 install --upgrade pip
        pip3 install -r python/requirements.txt
      
    - name: Configure CMake
      run: cmake -Bbuild -H. -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release

    - name: Tests
      run: |
        source ${PYTHON_VENV_ROOT}/bin/activate
        cd build
        pytest -k "not test_examples" tests
