name: Code Formatting

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set up uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt-get install clang-format
          uv sync --only-group dev

      - name: Check Python formatting
        run: .venv/bin/black --check .
          
      - name: Check C++ formatting
        run: | 
          find . -name "*.cpp" | xargs clang-format --style=file --dry-run -Werror
          find . -name "*.hpp" | xargs clang-format --style=file --dry-run -Werror
